
from cubeconstants import*

def RCLOCK():
    TEMP=CUBE[SFRONT][RBOT][CRIGHT]
    CUBE[SFRONT][RBOT][CRIGHT]=CUBE[SUNDER][RBOT][CRIGHT]
    CUBE[SUNDER][RBOT][CRIGHT]=CUBE[SBACK][RTOP][CLEFT]
    CUBE[SBACK][RTOP][CLEFT]=CUBE[STOP][RBOT][CRIGHT]
    CUBE[STOP][RBOT][CRIGHT]=TEMP

    TEMP=CUBE[SFRONT][RMID][CRIGHT]
    CUBE[SFRONT][RMID][CRIGHT]=CUBE[SUNDER][RMID][CRIGHT]
    CUBE[SUNDER][RMID][CRIGHT]=CUBE[SBACK][RMID][CLEFT]
    CUBE[SBACK][RMID][CLEFT]=CUBE[STOP][RMID][CRIGHT]
    CUBE[STOP][RMID][CRIGHT]=TEMP

    TEMP=CUBE[SFRONT][RTOP][CRIGHT]
    CUBE[SFRONT][RTOP][CRIGHT]=CUBE[SUNDER][RTOP][CRIGHT]
    CUBE[SUNDER][RTOP][CRIGHT]=CUBE[SBACK][RBOT][CLEFT]
    CUBE[SBACK][RBOT][CLEFT]=CUBE[STOP][RTOP][CRIGHT]
    CUBE[STOP][RTOP][CRIGHT]=TEMP

    TEMP=CUBE[SRIGHT][RTOP][CLEFT]
    CUBE[SRIGHT][RTOP][CLEFT]=CUBE[SRIGHT][RBOT][CLEFT]
    CUBE[SRIGHT][RBOT][CLEFT]=CUBE[SRIGHT][RBOT][CRIGHT]
    CUBE[SRIGHT][RBOT][CRIGHT]=CUBE[SRIGHT][RTOP][CRIGHT]
    CUBE[SRIGHT][RTOP][CRIGHT]=TEMP

    TEMP=CUBE[SRIGHT][RMID][CLEFT]
    CUBE[SRIGHT][RMID][CLEFT]=CUBE[SRIGHT][RBOT][CMID]
    CUBE[SRIGHT][RBOT][CMID]=CUBE[SRIGHT][RMID][CRIGHT]
    CUBE[SRIGHT][RMID][CRIGHT]=CUBE[SRIGHT][RTOP][CMID]
    CUBE[SRIGHT][RTOP][CMID]=TEMP

def RCOUNTERCLOCK():
    RCLOCK()
    RCLOCK()
    RCLOCK()

def LCOUNTERCLOCK():
    TEMP=CUBE[SFRONT][RBOT][CLEFT]
    CUBE[SFRONT][RBOT][CLEFT]=CUBE[SUNDER][RBOT][CLEFT]
    CUBE[SUNDER][RBOT][CLEFT]=CUBE[SBACK][RTOP][CRIGHT]
    CUBE[SBACK][RTOP][CRIGHT]=CUBE[STOP][RBOT][CLEFT]
    CUBE[STOP][RBOT][CLEFT]=TEMP

    TEMP=CUBE[SFRONT][RMID][CLEFT]
    CUBE[SFRONT][RMID][CLEFT]=CUBE[SUNDER][RMID][CLEFT]
    CUBE[SUNDER][RMID][CLEFT]=CUBE[SBACK][RMID][CRIGHT]
    CUBE[SBACK][RMID][CRIGHT]=CUBE[STOP][RMID][CLEFT]
    CUBE[STOP][RMID][CLEFT]=TEMP

    TEMP=CUBE[SFRONT][RTOP][CLEFT]
    CUBE[SFRONT][RTOP][CLEFT]=CUBE[SUNDER][RTOP][CLEFT]
    CUBE[SUNDER][RTOP][CLEFT]=CUBE[SBACK][RBOT][CRIGHT]
    CUBE[SBACK][RBOT][CRIGHT]=CUBE[STOP][RTOP][CLEFT]
    CUBE[STOP][RTOP][CLEFT]=TEMP

    TEMP=CUBE[SLEFT][RTOP][CLEFT]
    CUBE[SLEFT][RTOP][CLEFT]=CUBE[SLEFT][RTOP][CRIGHT]
    CUBE[SLEFT][RTOP][CRIGHT]=CUBE[SLEFT][RBOT][CRIGHT]
    CUBE[SLEFT][RBOT][CRIGHT]=CUBE[SLEFT][RBOT][CLEFT]
    CUBE[SLEFT][RBOT][CLEFT]=TEMP

    TEMP=CUBE[SLEFT][RMID][CLEFT]
    CUBE[SLEFT][RMID][CLEFT]=CUBE[SLEFT][RTOP][CMID]
    CUBE[SLEFT][RTOP][CMID]=CUBE[SLEFT][RMID][CRIGHT]
    CUBE[SLEFT][RMID][CRIGHT]=CUBE[SLEFT][RBOT][CMID]
    CUBE[SLEFT][RBOT][CMID]=TEMP

def LCLOCK():
    LCOUNTERCLOCK()
    LCOUNTERCLOCK()
    LCOUNTERCLOCK()

def TCOUNTERCLOCK():
    TEMP=CUBE[SFRONT][RTOP][CRIGHT]
    CUBE[SFRONT][RTOP][CRIGHT]=CUBE[SLEFT][RTOP][CRIGHT]
    CUBE[SLEFT][RTOP][CRIGHT]=CUBE[SBACK][RTOP][CRIGHT]
    CUBE[SBACK][RTOP][CRIGHT]=CUBE[SRIGHT][RTOP][CRIGHT]
    CUBE[SRIGHT][RTOP][CRIGHT]=TEMP

    TEMP=CUBE[SFRONT][RTOP][CMID]
    CUBE[SFRONT][RTOP][CMID]=CUBE[SLEFT][RTOP][CMID]
    CUBE[SLEFT][RTOP][CMID]=CUBE[SBACK][RTOP][CMID]
    CUBE[SBACK][RTOP][CMID]=CUBE[SRIGHT][RTOP][CMID]
    CUBE[SRIGHT][RTOP][CMID]=TEMP

    TEMP=CUBE[SFRONT][RTOP][CLEFT]
    CUBE[SFRONT][RTOP][CLEFT]=CUBE[SLEFT][RTOP][CLEFT]
    CUBE[SLEFT][RTOP][CLEFT]=CUBE[SBACK][RTOP][CLEFT]
    CUBE[SBACK][RTOP][CLEFT]=CUBE[SRIGHT][RTOP][CLEFT]
    CUBE[SRIGHT][RTOP][CLEFT]=TEMP

    TEMP=CUBE[STOP][RTOP][CLEFT]
    CUBE[STOP][RTOP][CLEFT]=CUBE[STOP][RTOP][CRIGHT]
    CUBE[STOP][RTOP][CRIGHT]=CUBE[STOP][RBOT][CRIGHT]
    CUBE[STOP][RBOT][CRIGHT]=CUBE[STOP][RBOT][CLEFT]
    CUBE[STOP][RBOT][CLEFT]=TEMP

    TEMP=CUBE[STOP][RTOP][CMID]
    CUBE[STOP][RTOP][CMID]=CUBE[STOP][RMID][CRIGHT]
    CUBE[STOP][RMID][CRIGHT]=CUBE[STOP][RBOT][CMID]
    CUBE[STOP][RBOT][CMID]=CUBE[STOP][RMID][CLEFT]
    CUBE[STOP][RMID][CLEFT]=TEMP

def TCLOCK():
    TCOUNTERCLOCK()
    TCOUNTERCLOCK()
    TCOUNTERCLOCK()

def UCLOCK():
    CUBEUP()
    CUBEUP()
    TCLOCK()
    CUBEUP()
    CUBEUP()

def UCOUNTERCLOCK():
    UCLOCK()
    UCLOCK()
    UCLOCK()

def MIDCLOCK():
    TEMP=CUBE[SFRONT][RBOT][CMID]
    CUBE[SFRONT][RBOT][CMID]=CUBE[SUNDER][RBOT][CMID]
    CUBE[SUNDER][RBOT][CMID]=CUBE[SBACK][RTOP][CMID]
    CUBE[SBACK][RTOP][CMID]=CUBE[STOP][RBOT][CMID]
    CUBE[STOP][RBOT][CMID]=TEMP

    TEMP=CUBE[SFRONT][RMID][CMID]
    CUBE[SFRONT][RMID][CMID]=CUBE[SUNDER][RMID][CMID]
    CUBE[SUNDER][RMID][CMID]=CUBE[SBACK][RMID][CMID]
    CUBE[SBACK][RMID][CMID]=CUBE[STOP][RMID][CMID]
    CUBE[STOP][RMID][CMID]=TEMP

    TEMP=CUBE[SFRONT][RTOP][CMID]
    CUBE[SFRONT][RTOP][CMID]=CUBE[SUNDER][RTOP][CMID]
    CUBE[SUNDER][RTOP][CMID]=CUBE[SBACK][RBOT][CMID]
    CUBE[SBACK][RBOT][CMID]=CUBE[STOP][RTOP][CMID]
    CUBE[STOP][RTOP][CMID]=TEMP

def MIDCOUNTERCLOCK():
    MIDCLOCK()
    MIDCLOCK()
    MIDCLOCK()

def MIDRIGHT():
    TEMP=CUBE[SFRONT][RMID][CMID]
    CUBE[SFRONT][RMID][CMID]=CUBE[SLEFT][RMID][CMID]
    CUBE[SLEFT][RMID][CMID]=CUBE[SBACK][RMID][CMID]
    CUBE[SBACK][RMID][CMID]=CUBE[SRIGHT][RMID][CMID]
    CUBE[SRIGHT][RMID][CMID]=TEMP

    TEMP=CUBE[SFRONT][RMID][CRIGHT]
    CUBE[SFRONT][RMID][CRIGHT]=CUBE[SLEFT][RMID][CRIGHT]
    CUBE[SLEFT][RMID][CRIGHT]=CUBE[SBACK][RMID][CRIGHT]
    CUBE[SBACK][RMID][CRIGHT]=CUBE[SRIGHT][RMID][CRIGHT]
    CUBE[SRIGHT][RMID][CRIGHT]=TEMP

    TEMP=CUBE[SFRONT][RMID][CLEFT]
    CUBE[SFRONT][RMID][CLEFT]=CUBE[SLEFT][RMID][CLEFT]
    CUBE[SLEFT][RMID][CLEFT]=CUBE[SBACK][RMID][CLEFT]
    CUBE[SBACK][RMID][CLEFT]=CUBE[SRIGHT][RMID][CLEFT]
    CUBE[SRIGHT][RMID][CLEFT]=TEMP

def MIDLEFT():
    MIDRIGHT()
    MIDRIGHT()
    MIDRIGHT()

def CUBEUP():
    RCLOCK()
    MIDCLOCK()
    LCOUNTERCLOCK()

def CUBEDOWN():
    CUBEUP()
    CUBEUP()
    CUBEUP()

def CUBERIGHT():
    TCOUNTERCLOCK()
    MIDRIGHT()
    UCLOCK()

def CUBELEFT():
    CUBERIGHT()
    CUBERIGHT()
    CUBERIGHT()

def CUBECLOCK():
    CUBEDOWN()
    CUBERIGHT()
    CUBEUP()

def CUBECOUNTERCLOCK():
    CUBECLOCK()
    CUBECLOCK()
    CUBECLOCK()

def FCLOCK():
    CUBEUP()
    TCLOCK()
    CUBEDOWN()

def FCOUNTERCLOCK():
    FCLOCK()
    FCLOCK()
    FCLOCK()

def BCLOCK():
    CUBEDOWN()
    TCOUNTERCLOCK()
    CUBEUP()

def BCOUNTERCLOCK():
    BCLOCK()
    BCLOCK()
    BCLOCK()


